
package juegoevent;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author karen
 */
public class eleccion extends javax.swing.JFrame {

   //bueno en esta clase lo que hago es dar a elegir al susuario como quiere jugar,
    //segun el boton se abriran las respectivas pantallas
    public eleccion() {
        initComponents();
   this.setSize(590,358);
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAdivinaVos = new javax.swing.JButton();
        btnAdivinoYo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnAdivinaVos.setBackground(new java.awt.Color(51, 255, 204));
        btnAdivinaVos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAdivinaVos.setText("Adivina vos");
        btnAdivinaVos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdivinaVosActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdivinaVos);
        btnAdivinaVos.setBounds(100, 230, 110, 23);

        btnAdivinoYo.setBackground(new java.awt.Color(51, 255, 204));
        btnAdivinoYo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAdivinoYo.setText("Adivino yo");
        btnAdivinoYo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdivinoYoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdivinoYo);
        btnAdivinoYo.setBounds(390, 230, 110, 23);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("        ¿Como queres jugar?");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 100, 252, 42);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegoevent/fondos/DD-Pink-Bokeh-Background-30188-Preview.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 590, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdivinoYoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdivinoYoActionPerformed
         personaAdivina personita=new personaAdivina();
         personita.setVisible(true);
      
    }//GEN-LAST:event_btnAdivinoYoActionPerformed

    private void btnAdivinaVosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdivinaVosActionPerformed
      
       
       compuAdivina compu=new compuAdivina();
       compu.setVisible(true);
       compu.adivinaVos();
       
       
       
    }//GEN-LAST:event_btnAdivinaVosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(eleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(eleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(eleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(eleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new eleccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdivinaVos;
    private javax.swing.JButton btnAdivinoYo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
